# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 01:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import helper.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('acronym', models.CharField(max_length=3, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[helper.validators.is_alpha_num])),
                ('field_type', models.CharField(choices=[(b'text', b'text'), (b'number', b'number'), (b'textarea', b'textarea')], default=b'text', max_length=20)),
                ('max_length', models.PositiveIntegerField(default=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[helper.validators.is_alpha_num])),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[helper.validators.is_alpha_num_words])),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTemplateOptions',
            fields=[
                ('field_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.FieldTemplate')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('formset', models.CharField(blank=True, max_length=30)),
                ('autocomplete', models.BooleanField(default=True)),
                ('placeholder', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplateOptions',
            fields=[
                ('form_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='builder.FormTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='builder.Department'),
        ),
        migrations.AddField(
            model_name='formset',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formsets', to='builder.FormTemplate'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='form_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_data', to='builder.FormTemplate'),
        ),
        migrations.AddField(
            model_name='fieldtemplate',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_templates', to='builder.FormTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='formtemplate',
            unique_together=set([('name', 'department')]),
        ),
        migrations.AlterUniqueTogether(
            name='formset',
            unique_together=set([('name', 'form_template')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldtemplate',
            unique_together=set([('name', 'form_template')]),
        ),
    ]
