# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20160229_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtemplateoptions',
            name='formset',
            field=models.CharField(blank=True, choices=[('', '')], max_length=30),
        ),
    ]
