# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20160229_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtemplateoptions',
            name='formset',
        ),
    ]
