# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_remove_fieldtemplateoptions_formset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtemplateoptions',
            name='formset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_template_options', to='builder.FormSet'),
        ),
    ]
